### ISSUE TITLE
Update `quinn-proto` to 0.8?

### ISSUE THREAD

**Issue by thomaseizinger** [ipfs-rust/quinn-noise#5]
In the [release notes](https://github.com/quinn-rs/quinn/releases/tag/0.8.0), it says that the configuration has been massively simplified. I haven't yet attempted an upgrade myself. Do you plan on upgrading this? Wouldn't want to do duplicate work :)

**Comment by dvc94ch** [comment]
Since the open libp2p-quic PR dropped support I haven't spent anymore time on it. Might try and see if anything can be salvaged once the PR gets merged

**Comment by dvc94ch** [comment]
Done and released in 0.4.0
